version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build-and-test:
    executor: node/default
    working_directory: ~/ASK_2020_lab2/server/
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm test
          
workflows:
    build-and-test:
      jobs:
        - build-and-test
